modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"
issueTrackerURL="http://github.com/romangraef/tagtooltip/issues"
[[mods]]
modId="tagtooltip"
version="${file.jarVersion}"
displayName="Tag Tooltips"
updateJSONURL="http://myurl.me/" # todo update url
displayURL="http://github.com/romangraef/tagtooltip"
logoFile="tagtooltip.png"
credits=""
authors="Roman Gräf <hello@romangraef.com>"
description='''
Adds tooltips to items to show the tags that they have.
'''
[[dependencies.tagtooltip]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="CLIENT"
